Update langchain-observability-snippet.ipynb
GoogleCloudPlatform/applied-ai-engineering-samples pull request #12
Opened 2023-12-01 14:49 UTC by jpantsjoha

fixing the auth snippet section

2023-12-01 15:45 UTC, RajeshThallam commented
@jpantsjoha Thanks for the contribution. Can you please look at the failed checks? You may have to sign the CLA?

2023-12-07 22:28 UTC, michaelwsherman requested changes
LGTM and thanks for this. But @jpantsjoha we still need a CLA and this should be refactored to point to the new location for this notebook (applied-ai-engineering-samples/genai-on-vertex-ai/langchain_observability_snippet/langchain-observability-snippet.ipynb .

2024-04-16 10:50 UTC, jpantsjoha commented
done. CLA signed.

2024-05-09 16:50 UTC, michaelwsherman commented
Still errors -- click into the CLA error, make sure you've signed it with that email.

Also, there's a merge conflict, please resolve that so it can be merged into main.

Thank you!

2025-05-07 22:53 UTC, closed without merging

2025-05-07 22:53 UTC, RajeshThallam commented
Notebook discontinued as part of Gemini 2.x migration #168